---
# Required versions of things:
# CMake: 3.15
# Boost 1.73
# Proj 7.2.0


cmake_pkg: cmake
cmake_cmd: cmake
# Recognized values for cmake_source are:
# * package: Use package manager to install cmake
# * upstream: Use binary archive from upstream CMake downloads
# Default is 'package'
cmake_source: package

cmake_upstream_baseurl: https://cmake.org/files/LatestRelease/
cmake_upstream_json: cmake-latest-files-v1.json 

# Options to pass to cmake for mapnik compile
cmake_opts: ''

boost_pkgs: boost
# Recognized values for boost_source are:
# * package: Use package manager to install boost
# * upstream: Build upstream boost libraries needed by mapnik
# Default is 'package'
boost_source: package

# Packages for mapnik required build tools
mapnik_build_tools: ''
# Packages for mapnik required dependencies
mapnik_build_deps: ''
