---
# We use the folded quote operator, '>', to make long
# package lists more human readable. This operator "folds"
# newlines into spaces. Most Ansible package modules don't
# care if there are spaces in the comma-separated package
# list, but the zypper one fails if there are, hence blocks
# followed with a replace to remove spaces.

boost_pkgs_list: >
    boost-devel,libboost_filesystem-devel,libboost_system-devel,
    libboost_regex-devel,libboost_program_options-devel
boost_pkgs: '{{ boost_pkgs_list | replace(" ","") }}'
boost_build_deps: python3-devel
proj_dev_pkg: proj-devel
mapnik_build_tools: bzip2,make,gcc,gcc-c++
mapnik_build_deps_list: >
    libicu-devel,freetype2-devel,harfbuzz-devel,libxml2-devel,
    libpng16-devel,libjpeg8-devel,libtiff-devel,libwebp-devel,cairo-devel,
    gdal-devel,postgresql13-server-devel,sqlite3-devel,
    libqt5-qtbase-devel
mapnik_build_deps: '{{ mapnik_build_deps_list | replace(" ","") }}'
