---
- name: Import PGDG repo key
  apt_key:
    url: "{{ pgdg_apt_repokey_url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg

- name: Install PGDG repo file
  apt_repository:
    repo: "deb {{ pgdg_apt_repo_url }} {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: pgdg.list
