---
- name: Import PGDG repo key
  rpm_key:
    key: "{{ pgdg_yum_repokey_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

- name: Install PGDG repo package
  yum:
    name: "{{ pgdg_yum_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
