---
- name: Import PGDG repoo key
  rpm_key:
    key: "{{ pgdg_repo_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10

- name: Install PGDG repo package
  yum:
    name: "{{ pgdg_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
